### ISSUE TITLE
remaining tasks of job manager/master failover

### ISSUE THREAD

**Issue by amyangfei** [hanfei1991/microcosm#190]
- [x] job manager persists job master meta before `CreateWorker`, when both job manager and job master crash before job master meta is persisted in job master, the job information will be lost. #193
- [x] Support job pause or finish of job management in job manager
- [x] Support rescheduling pending jobs if no ack is received for long time. #199 
- [x] Refine data structure of `MasterMetaKVData `, #193 https://github.com/hanfei1991/microcosm/blob/d0a23069e069e9ffa1d735597e70e0a7adc3701b/lib/common.go#L121
- [x] Fix the bug that worker treats transferred master as timeout before any heartbeat is received. #191
- [x] Fix the bug that status update handler is not removed after worker is offline. #195
- [x] Fix on master recovered is not called in job manager startup procedure. #196 
- [x] Solve worker message handler ignores late messages because of server master always uses the same id. #198
- [x] Test only job master exits and restarts, the system can failover normally. #355
