### ISSUE TITLE
Todo list for metastore

### ISSUE THREAD

**Issue by maxshuang** [hanfei1991/microcosm#298]
- [ ] New meta client interface for framework metastore  
  - [ ] meta client query interface
  - [ ] replace framework kv client
  - [ ] covering other needs for framework access 
- [ ] Multi-tenant support for user metastore
- [ ] KVclient  implement for TiDB
