### ISSUE TITLE
todo list for adopting the master-worker framework

### ISSUE THREAD

**Issue by liuzix** [hanfei1991/microcosm#88]
- [ ] Merge the implementation #84 
- [ ] Add unit tests for the implementation.
- [ ] Modify `runtime` to provide semantics compatible to the master-worker framework
- [ ] Integrate `MessageRouter` with cluster membership management mechanism.
- [ ] Whole system Integration tests for the master-worker framework.
- [ ] Migrate existing Demo.

**Comment by amyangfei** [comment]
- [ ] master failover
- [ ] worker failover
- [ ] job manager manages job master
- [ ] executor registers job master and worker
